export const stocksData = [
  {
    id: 'stock_001',
    companyName: 'HDFC Bank',
    tickerSymbol: 'HDFCBANK',
    exchangeName: 'NSE',
    sector: 'Financial',
    buyPrice: 1490,
    quantityHeld: 50,
  },
  {
    id: 'stock_002',
    companyName: 'Bajaj Finance',
    tickerSymbol: 'BAJFINANCE',
    exchangeName: 'NSE',
    sector: 'Financial',
    buyPrice: 6466,
    quantityHeld: 15,
  },
  {
    id: 'stock_003',
    companyName: 'ICICI Bank',
    tickerSymbol: 'ICICIBANK',
    exchangeName: 'NSE',
    sector: 'Financial',
    buyPrice: 780,
    quantityHeld: 84,
  },
  {
    id: 'stock_004',
    companyName: 'Bajaj Housing',
    tickerSymbol: 'BAJAJHLDNG',
    exchangeName: 'NSE',
    sector: 'Financial',
    buyPrice: 130,
    quantityHeld: 504,
  },
  {
    id: 'stock_005',
    companyName: 'Savani Financials',
    tickerSymbol: '511577',
    exchangeName: 'BOM',
    sector: 'Financial',
    buyPrice: 24,
    quantityHeld: 1080,
  },
  {
    id: 'stock_006',
    companyName: 'Affle India',
    tickerSymbol: 'AFFLE',
    exchangeName: 'NSE',
    sector: 'Technology',
    buyPrice: 1151,
    quantityHeld: 50,
  },
  {
    id: 'stock_007',
    companyName: 'LTI Mindtree',
    tickerSymbol: 'LTIM',
    exchangeName: 'NSE',
    sector: 'Technology',
    buyPrice: 4775,
    quantityHeld: 16,
  },
  {
    id: 'stock_008',
    companyName: 'KPIT Tech',
    tickerSymbol: 'KPITTECH',
    exchangeName: 'NSE',
    sector: 'Technology',
    buyPrice: 672,
    quantityHeld: 61,
  },
  {
    id: 'stock_009',
    companyName: 'Tata Tech',
    tickerSymbol: 'TATATECH',
    exchangeName: 'NSE',
    sector: 'Technology',
    buyPrice: 1072,
    quantityHeld: 63,
  },
  {
    id: 'stock_010',
    companyName: 'BLS E-Services',
    tickerSymbol: 'BLS',
    exchangeName: 'NSE',
    sector: 'Technology',
    buyPrice: 232,
    quantityHeld: 191,
  },
  {
    id: 'stock_011',
    companyName: 'Tanla',
    tickerSymbol: 'TANLA',
    exchangeName: 'NSE',
    sector: 'Technology',
    buyPrice: 1134,
    quantityHeld: 45,
  },
  {
    id: 'stock_012',
    companyName: 'Dmart',
    tickerSymbol: 'DMART',
    exchangeName: 'NSE',
    sector: 'Consumer',
    buyPrice: 3777,
    quantityHeld: 27,
  },
  {
    id: 'stock_013',
    companyName: 'Tata Consumer',
    tickerSymbol: 'TATACONSUM',
    exchangeName: 'NSE',
    sector: 'Consumer',
    buyPrice: 845,
    quantityHeld: 90,
  },
  {
    id: 'stock_014',
    companyName: 'Pidilite',
    tickerSymbol: 'PIDILITIND',
    exchangeName: 'NSE',
    sector: 'Consumer',
    buyPrice: 2376,
    quantityHeld: 36,
  },
  {
    id: 'stock_015',
    companyName: 'Tata Power',
    tickerSymbol: 'TATAPOWER',
    exchangeName: 'NSE',
    sector: 'Power',
    buyPrice: 224,
    quantityHeld: 225,
  },
  {
    id: 'stock_016',
    companyName: 'KPI Green',
    tickerSymbol: 'KPIGREEN',
    exchangeName: 'NSE',
    sector: 'Power',
    buyPrice: 875,
    quantityHeld: 50,
  },
  {
    id: 'stock_017',
    companyName: 'Suzlon',
    tickerSymbol: 'SUZLON',
    exchangeName: 'NSE',
    sector: 'Power',
    buyPrice: 44,
    quantityHeld: 450,
  },
  {
    id: 'stock_018',
    companyName: 'Gensol',
    tickerSymbol: 'GENSOL',
    exchangeName: 'NSE',
    sector: 'Power',
    buyPrice: 998,
    quantityHeld: 45,
  },
  {
    id: 'stock_019',
    companyName: 'Hariom Pipes',
    tickerSymbol: 'HARIOMPIPE',
    exchangeName: 'NSE',
    sector: 'Industrial',
    buyPrice: 580,
    quantityHeld: 60,
  },
  {
    id: 'stock_020',
    companyName: 'Astral',
    tickerSymbol: 'ASTRAL',
    exchangeName: 'NSE',
    sector: 'Industrial',
    buyPrice: 1517,
    quantityHeld: 56,
  },
  {
    id: 'stock_021',
    companyName: 'Polycab',
    tickerSymbol: 'POLYCAB',
    exchangeName: 'NSE',
    sector: 'Industrial',
    buyPrice: 2818,
    quantityHeld: 28,
  },
  {
    id: 'stock_022',
    companyName: 'Clean Science',
    tickerSymbol: 'CLEAN',
    exchangeName: 'NSE',
    sector: 'Materials',
    buyPrice: 1610,
    quantityHeld: 32,
  },
  {
    id: 'stock_023',
    companyName: 'Deepak Nitrite',
    tickerSymbol: 'DEEPAKNTR',
    exchangeName: 'NSE',
    sector: 'Materials',
    buyPrice: 2248,
    quantityHeld: 27,
  },
  {
    id: 'stock_024',
    companyName: 'Fine Organic',
    tickerSymbol: 'FINEORG',
    exchangeName: 'NSE',
    sector: 'Materials',
    buyPrice: 4284,
    quantityHeld: 16,
  },
  {
    id: 'stock_025',
    companyName: 'Gravita',
    tickerSymbol: 'GRAVITA',
    exchangeName: 'NSE',
    sector: 'Materials',
    buyPrice: 2037,
    quantityHeld: 8,
  },
  {
    id: 'stock_026',
    companyName: 'SBI Life',
    tickerSymbol: 'SBILIFE',
    exchangeName: 'NSE',
    sector: 'Financial',
    buyPrice: 1197,
    quantityHeld: 49,
  },
  {
    id: 'stock_027',
    companyName: 'Infosys',
    tickerSymbol: 'INFY',
    exchangeName: 'NSE',
    sector: 'Technology',
    buyPrice: 1647,
    quantityHeld: 36,
    status: 'sold',
    sellPrice: 1920,
  },
  {
    id: 'stock_028',
    companyName: 'Happiest Minds',
    tickerSymbol: 'HAPPSTMNDS',
    exchangeName: 'NSE',
    sector: 'Technology',
    buyPrice: 1103,
    quantityHeld: 45,
    status: 'sold',
    sellPrice: 716,
  },
  {
    id: 'stock_029',
    companyName: 'Easemytrip',
    tickerSymbol: 'EASEMYTRIP',
    exchangeName: 'NSE',
    sector: 'Consumer',
    buyPrice: 20,
    quantityHeld: 1332,
    status: 'sold',
    sellPrice: 15.5,
  },
];
